version: "3.2"

services:
  node-exporter:
    image: quay.io/prometheus/node-exporter:v1.6.1
    volumes:
      - '/:/host:ro'
    command:
      - '--path.rootfs=/host'
    deploy:
      mode: global
    networks:
      - monitoring_net


networks:
  monitoring_net:
    driver: overlay
    attachable: true